name: Build and Deploy
on:
  push:
    branches:
      - main  # This workflow will be triggered when changes are pushed to main branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build_webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12'  # Sets up Node.js version 14

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            gatsby/node_modules/
            gatsby/.cache/
            public/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }} # Creates a unique key for the cache based on the OS and the hash of package-lock.json file
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install and Build
        run: |
          rm -f -R public
          cd gatsby
          npm install
          ./node_modules/.bin/gatsby build --prefix-paths

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public


  # Deployment job
  Deploy_webpage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Build_webpage
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2