name: Test Conda ARM64

on:
  workflow_dispatch:

  
jobs:
  build_arm64:
    name: Install album solution on ARM64
    runs-on: [self-hosted, macOS, ARM64]
    
    # Conda needs to use login mode
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - name: Clone actual DL4MicEverywhere-album repository
        uses: actions/checkout@v4
      - name: Set up album's Miniconda environment
        uses: conda-incubator/setup-miniconda@v3
        with:          
        #   miniforge-version: latest
        #   mamba-version: "*"
          use-mamba: true
          auto-update-conda: false
          auto-activate-base: false 
          python-version: 3.12 # Python version needs to be between 3.7 and 3.12
          activate-environment: album
          environment-file: .tools/actions_utils/album_enviornment.yml 
          condarc-file: .tools/actions_utils/album_condarc.yml # Optional runtime configuration
          run-post: true # Run post cleanup step